### ISSUE TITLE
Don't use default ILogger implementation

### ISSUE THREAD

**Issue by srpeirce** [purplebricks/Pat.Subscriber#21]
Hello @DaveAurionix,
(CC @ilivewithian @AndyRB )

## What is the problem

In a number of places we are injecting `ILogger`, I believe this is bad practice.

e.g.
```
public BatchProcessor(BatchProcessingBehaviourPipeline batchProcessingBehaviourPipeline, BatchFactory batchFactory, ILogger log)
```

I believe we should be injecting `ILogger<T>`, so in the instance above:
```
public BatchProcessor(BatchProcessingBehaviourPipeline batchProcessingBehaviourPipeline, BatchFactory batchFactory, ILogger<BatchProcessor> log)
```
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1

### 1. Pat logs everything under the same name, which potentially make debugging difficult.

We are having to register a default implementation of ILogger (as per the extension method https://github.com/purplebricks/Pat.Subscriber/blob/b67673075910b99680b12f033d1f3940067540b7/Pat.Subscriber.NetCoreDependencyResolution/PatLiteDependencyHelper.cs)
```
 public static IServiceCollection AddDefaultPatLogger(this IServiceCollection serviceCollection)
        {
            return serviceCollection.AddSingleton(s => s.GetRequiredService<ILoggerFactory>().CreateLogger("Pat"));
        }
```

### 2. If another provider uses `ILogger` instead of `ILogger<T>` we will be writing logs as "Pat" which could be misleading and confusing.

- Without registering a default ILogger, if I accidentally use `ILogger` instead of `ILogger<T>` in my class I would expect IOC to error, saying it cannot find an instance. Instead I will get the Pat Logger.
- If another third party library was to use ILogger I would have no way to differentiate between the 2 loggers

## What is affected?

On quick search we inject ILogger:

- Pat.Subscriber/BatchProcessor.cs
- Pat.Subscriber/MultipleBatchProcessor.cs 
- Pat.Subscriber/SubscriberRules/RuleApplier.cs 
- Pat.Subscriber/BatchProcessing/DefaultBatchProcessingBehaviour.cs 
- Pat.Subscriber/MessageProcessor.cs 
- Pat.Subscriber/MessageReceiverFactory.cs 
- Pat.Subscriber/MessageProcessing/DefaultMessageProcessingBehaviour.cs 
- Pat.Subscriber/SubscriptionBuilder.cs 
- Pat.Subscriber/Subscriber.cs 
- Pat.Subscriber/AzureServiceBusMessageReceiverFactory.cs 
- Pat.Subscriber/CicuitBreaker/CircuitBreakerBatchProcessingBehaviour.cs

**Comment by srpeirce** [comment]
@DaveAurionix Before updating usages to `ILogger<T>` I wanted to check with yourself that we didn't choose `ILogger` for a reason

**Comment by DaveAurionix** [comment]
@srpeirce Sorry for the delay, I had to run some tests before I could form an opinion.  Using ILogger inverts control so that the consumer has control over the question raised above (by setting up one or many loggers in the IoC container using CreateLogger or CreateLogger<T> as they wish - their choice).  It supports the scenario your describe along with others.  However, I agree that the choice and control does not add any benefit and using ILogger<ConcreteType> in Pat's constructors would be better.

For Pat.Subscriber I think that's an obvious change as subscribers are all encouraged to use .NET Core's dependency injection, or an IoC tech that supports/adapts-into .NET Core's.

For Pat.Sender we'd be introducing more differences between the .NET Standard package and the .NET Framework (StructureMap) package, which is sad but necessary.  Would like to stop needing to support that last one!

**Comment by ilivewithian** [comment]
@DaveAurionix we're starting to reduce our reliance on structuremap, it's still going to be there for a while, but moving away from it is on the roadmap.

**Comment by srpeirce** [comment]
Okay cool, so based on what you said I am good to tackle this for Pat.Subscriber.

**Comment by srpeirce** [comment]
I'll probably look at getting this done early next week. FYI this will involve some changes around IOC as we currently "new up" some dependencies in the Subscriber class, we should be able to inject these.

https://github.com/purplebricks/Pat.Subscriber/blob/master/Pat.Subscriber/Subscriber.cs
